import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import Providers from "./Providers";
import { Session } from "next-auth";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Riwi LinkUp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,session
}: Readonly<{
  children: React.ReactNode;
  session: Session | null;
}>) {
  return (
    <html lang="en">
       <body>
        <AppRouterCacheProvider>
           <Providers session={session}>
              {children}
           </Providers>
        </AppRouterCacheProvider>
       </body>
     </html>
  );
}
